### ISSUE TITLE
iPhone 6 not support 

### ISSUE THREAD

**Issue by CrazyCoderShi** [exyte/ARTetris#1]
[Session] Unable to run the session, configuration is not supported on this device: <ARSessionConfiguration: 0x1c4279300 worldAlignment=Gravity lightEstimation=Enabled>

**Comment by CrazyCoderShi** [comment]
alright, 
iPhone 6 does not support indeed😂

See about it there:
https://www.cnet.com/news/which-iphone-ipad-compatible-arkit-augmented-ios-11/

**Comment by ystrot** [comment]
Yep, waiting for a next beta from Apple where ARSessionConfiguration will be supported for iPhone 6 (however with a lower quality).

**Comment by CrazyCoderShi** [comment]
@ystrot Really, that great
