### ISSUE TITLE
tetris doesn't show

### ISSUE THREAD

**Issue by markzhong88** [exyte/ARTetris#2]
Hi,

This is a very interesting idea using ar. I try to run the app, but it doesn't show any Tetris on my screen, only a camera scene....

**Comment by Paladinfeng** [comment]
just because func renderer didAdd is hardly to be call

**Comment by ystrot** [comment]
Hi Mark,

Camera scene is okay. Then you need to point your camera to some plane (floor, table top, etc.). You may need to move your device a little bit to force ARKit to find the plane bounds. Once it will be found, you will see Tetris well on this plane.

**Comment by markzhong88** [comment]
Hi Yuri,

I found the Tetris. It would be better to change the size of the whole tetris, than user can play on their table or small plane. Anyway, it's awesome!

**Comment by ystrot** [comment]
Thanks! Agree with you, I will add this feature in the nearest time.
