### ISSUE TITLE
Crash when runningon iPad Air

### ISSUE THREAD

**Issue by TripwireNL** [exyte/ARTetris#4]
Hi,

I'm trying to run the project on my iPad Air but i'm getting the following error:
ARTetris[3259:958330] -[MTLTextureDescriptorInternal validateWithDevice:], line 778: error 'MTLTextureDescriptor has invalid pixelFormat (520).'
-[MTLTextureDescriptorInternal validateWithDevice:]:778: failed assertion `MTLTextureDescriptor has invalid pixelFormat (520).

Don't really know what's going on yet but maybe you have a clue?

**Comment by ystrot** [comment]
Hi Sebastian,

Currently ARKit works only on devices which have A9 processor or better. You need to use at least iPad or iPhone 6S.
