### ISSUE TITLE
'init()' is unavailable beta 5

### ISSUE THREAD

**Issue by mcnahum** [exyte/ARTetris#8]
on beta 5, after setting the new function (ARConfiguration & ARWorldTrackingConfiguration ) 

I've an error 'init()' is unavailable ... any idea?

**Comment by amarunko** [comment]
you can use AROrientationTrackingConfiguration() instead in places where ARWorldTrackingConfiguration() is unavailable. ARConfiguration is abstract class now, that's why init() of ARConfiguration generate compile time error

**Comment by amarunko** [comment]
Fixed
