### ISSUE TITLE
Cannot see the tetris game.

### ISSUE THREAD

**Issue by dandreikiv** [exyte/ARTetris#9]
I have downloaded the project and run in on iPhone SE with iOS 11 beta 6, built with Xcode 9 beta 5 (9M202q). The project runs but I do not see any tetris game.

**Comment by ystrot** [comment]
Hey! Check out these recommendations to start playing: https://github.com/exyte/ARTetris/issues/2#issuecomment-313354006

**Comment by dandreikiv** [comment]
Thanks Yuri, it works. It is amazing.
